analyzer/urls.py
from django.conf.urls.static import static
from django.urls import path

from imganalyzer import settings
from . import views
from analyzer import views as analyzer_views

app_name = 'analyzer'

urlpatterns = [

    # Home
    path('', analyzer_views.Home.as_view(), name='home'),

    # Images
    path('image/create', analyzer_views.ImageForm.as_view(), name='image_create'),
    path('image/list', analyzer_views.ImageList.as_view(), name='image_list'),
    path('datatable/image/<pk>/categories', views.ImageCategoriesDatatable.as_view(), name='image_categories_dt'),
    path('image/<pk>/category/add', views.ImageCategoryAdd.as_view(), name='image_category_add'),
    path('image/<pk>/category/remove', views.ImageCategoryRemove.as_view(), name='image_category_remove'),

    # Category
    path('category/create', analyzer_views.CategoryForm.as_view(), name='category_create'),
    path('category/list', analyzer_views.CategoryList.as_view(), name='category_list'),
    path('image/<pk>/categories/update', analyzer_views.ImageCategoriesUpdate.as_view(), name='image_cat_update'),
    path('category/ajax_list', analyzer_views.CategoryAjaxList.as_view(), name='category_ajax_list'),

    path('datatable/categories', analyzer_views.CategoriesDatatable.as_view(), name='categories_dt'),
    path('categories', analyzer_views.CategoriesListView.as_view(), name='categories'),
    path('categories/remove', analyzer_views.CategoriesRemove.as_view(), name='categories_remove'),
    path('category/update/<pk>', analyzer_views.CategoryForm.as_view(), name='category_update'),

    path('predict/image/<pk>', analyzer_views.PredictImageCategory.as_view(), name='predict_image'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imganalyzer/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from analyzer import views as analyzer_views

urlpatterns = [

    path('', include('analyzer.urls', namespace='analyzer')),

    # Auth
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login'), name='logout'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done', analyzer_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    # Admin
    path('admin/', admin.site.urls),
]

analyzer/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500, unique=True)
    description = models.TextField(null=True, blank=True)

    def _generate_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        i = 1
        while Category.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, i)
            i += 1
        return unique_slug

    def __str__(self):
        return self.title


class Image(models.Model):
    STATUS_CHOICES = (
        ('fake', 'Fake'),
        ('real', 'Real'),
        ('not_analyzed', 'Not Analyzed')
    )

    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500, unique=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='analyzer_images')
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='images')
    size = models.IntegerField()
    extension = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='not_analyzed')
    categories = models.ManyToManyField(Category)

    def _get_extension(self):
        name, extension = os.path.splitext(self.image.name)
        return extension

    # It Generates a unique slug based on the existent Images in database
    def _generate_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        i = 1
        while Image.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, i)
            i += 1
        return unique_slug

    def save_model(self, request, obj, form, change):
        if not obj.id:
            obj.created_by = request.user
            obj.slug = obj._generate_unique_slug()
            obj.extension = obj.image._get_extension()
        super().save_model(request, obj, form, change)

    def save(self, *args, **kwargs):
        if not self.size and self.image.size > 0:
            self.size = self.image.size
        else:
            self.size = 0
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

analyzer/forms.py
from django import forms
from django.contrib.auth.models import Group

from analyzer.models import Image, Category


class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('image','title','description',)

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title', 'description',)

analyzer/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import PasswordContextMixin
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import TemplateView, FormView, ListView, DetailView

# Home Template View
from django.views.generic.base import View
from django_datatables_view.base_datatable_view import BaseDatatableView

from analyzer.forms import ImageForm, CategoryForm
from analyzer.helpers import AjaxResponseMixin, AJAXLoadMixin, AJAXDropdownMixin, AJAXMixin, RemoveObjectsMixin
from analyzer.models import Category, Image
from analyzer.helpers import DatatableTransformations as dt_helper

from keras.models import load_model
import argparse
import pickle
import cv2
from keras import backend as K


class Home(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/home/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_info'] = self.request.user
        context['category_count'] = Category.objects.count()
        context['images_count'] = Image.objects.count()
        return context

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class PasswordResetDoneView(PasswordContextMixin, TemplateView):
    template_name = 'registration/login.html'
    title = ('Password reset sent')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['password_reset_done'] = True
        return context


class ImageForm(LoginRequiredMixin, AjaxResponseMixin, View):
    template_name = 'dashboard/image/image_form.html'  # Form modal template
    modal_title = ''  # Modal title that should be displayed
    model = Image  # Model of this Class based view
    form_class = ImageForm  # Form of this Model

    def saveFormLogic(self, form):
        img = form.save(commit=False)
        img.created_by = self.request.user
        img.slug = img._generate_unique_slug()
        img.extension = img._get_extension()
        if not img.size and img.image.size > 0:
            img.size = img.image.size
        else:
            img.size = 0
        img.save()
        return img


class CategoryForm(LoginRequiredMixin, AjaxResponseMixin, FormView):
    template_name = 'dashboard/image/category_form.html'  # Form modal template
    modal_title = ''  # Modal title that should be displayed
    model = Category  # Model of this Class based view
    form_class = CategoryForm  # Form of this Model

    def saveFormLogic(self, form):
        category = form.save(commit=False)
        category.slug = category._generate_unique_slug()
        category.save()
        return category


class ImageList(LoginRequiredMixin, ListView):
    template_name = 'dashboard/image/image_list.html'
    model = Image
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        if not request.GET._mutable:
            request.GET._mutable = True
        request.GET['page'] = request.GET['block']

        return super().get(self, request, *args, **kwargs)


class CategoryList(LoginRequiredMixin, ListView):
    template_name = 'dashboard/image/category_list.html'
    model = Category
    paginate_by = 50


class ImageCategoriesUpdate(LoginRequiredMixin, AJAXLoadMixin, DetailView):
    model = Image
    template_name = 'dashboard/image/image_categories_update.html'
    modal_title = 'Image Categories'
    add_context = {}
    object = None

    def get(self, request, pk=None, *args, **kwargs):
        if pk is not None:
            self.object = get_object_or_404(self.model, pk=pk)
            self.add_context = {}
        return self.loadAJAXResponse()


class CategoryAjaxList(LoginRequiredMixin, AJAXDropdownMixin, ListView):
    model = Category

    def query(self, find, pk):

        if find is not None:
            object_list = self.model.objects.filter(title__contains=find).order_by('-id')[:20]
        else:
            object_list = self.model.objects.order_by('-id')[:20]

        result = list()

        for item in object_list:
            result.append({
                'id': item.id,
                'name': item.title
            })
        return result


class ImageCategoriesDatatable(LoginRequiredMixin, BaseDatatableView):
    model = Category
    columns = ['title', 'actions']
    max_display_length = 500

    def get_initial_queryset(self):
        pk = self.kwargs['pk']
        if not pk:
            raise NotImplementedError("Need to provide a model or implement get_initial_queryset!")
        image = Image.objects.get(pk=pk)
        return self.model.objects.filter(image__exact=image)

    def render_column(self, row, column):
        pk = self.kwargs['pk']
        image = Image.objects.get(pk=pk)
        if column == 'title':
            return dt_helper.highlightBlue(row.title)
        elif column == 'actions':
            return render_to_string('dashboard/image/image_categories_dt_buttons.html',
                                    {"category": row, 'image': image})
        else:
            return super(ImageCategoriesDatatable, self).render_column(row, column)


class ImageCategoryRemove(LoginRequiredMixin, PermissionRequiredMixin, AJAXLoadMixin, DetailView):
    permission_required = 'foundation.change_account'
    model = Image
    template_name = 'dashboard/image/image_categories_update.html'
    modal_title = 'Image Categories'
    add_context = {}
    object = None

    def post(self, request, pk=None, *args, **kwargs):
        if pk is not None:
            image = get_object_or_404(self.model, pk=pk)
            category_id = self.request.POST.get('category_id')
            category = Category.objects.get(id=category_id)
            cnt = image.categories.count()
            image.categories.remove(category)
            if image.categories.count() < cnt:
                self.add_context['status'] = True
                self.add_context['title'] = 'Success'
                self.add_context['msg'] = 'Category ' + str(category.title) + ' has been removed'
            else:
                self.add_context['status'] = False
                self.add_context['title'] = 'Fail'
                self.add_context['msg'] = 'Impossible to remove ' + str(category.title) + ''

            self.object = image

        return self.loadAJAXResponse()


class ImageCategoryAdd(LoginRequiredMixin, PermissionRequiredMixin, AJAXLoadMixin, DetailView):
    permission_required = 'foundation.change_account'
    model = Image
    template_name = 'dashboard/image/image_categories_update.html'
    modal_title = 'Image Categories'
    add_context = {}
    object = None

    def post(self, request, pk=None, *args, **kwargs):
        if pk is not None:
            image = get_object_or_404(self.model, pk=pk)
            category_id = self.request.POST.get('category_id')
            category = Category.objects.get(id=category_id)

            if category in image.categories.all():
                self.add_context['status'] = False
                self.add_context['title'] = 'Fail'
                self.add_context['msg'] = 'This category is already included!'
            else:
                cnt = image.categories.count()
                image.categories.add(category)
                if image.categories.count() > cnt:
                    self.add_context['status'] = True
                    self.add_context['title'] = 'Success'
                    self.add_context['msg'] = 'Category ' + str(category.title) + ' has been included!'
                else:
                    self.add_context['status'] = False
                    self.add_context['title'] = 'Fail'
                    self.add_context['msg'] = 'Impossible to include ' + str(category.title)

            self.object = image

        return self.loadAJAXResponse()


class CategoriesDatatable(LoginRequiredMixin, BaseDatatableView):
    model = Category
    columns = ['check',
               'title',
               'slug',
               'description',
               'actions']
    order_columns = columns
    max_display_length = 500

    def render_column(self, row, column):
        if column == 'check':
            return dt_helper.generateRowCheckBox(row.id)
        if column == 'title':
            return dt_helper.highlightOrange(row.title)
        if column == 'slug':
            return dt_helper.printSlug(row.slug)
        elif column == 'actions':
            return render_to_string('dashboard/category/partial_datatable_buttons.html', {"category": row})
        else:
            return super(CategoriesDatatable, self).render_column(row, column)


class CategoriesListView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/category/categories.html'


class CategoriesRemove(LoginRequiredMixin, AJAXMixin, RemoveObjectsMixin, View):
    model = Category

    # Deletion Logic
    def deleteObject(self, object):
        name = '<b>' + object.title + '</b> - '
        if object.delete():
            return (None, None)
        else:
            return ('error', name + 'Impossible to remove')


class PredictImageCategory(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/home/predict.html'

    def get(self, request, *args, **kwargs):
        results = {}

        if 'pk' in kwargs:

            # try:

            img = Image.objects.get(pk=kwargs['pk'])
            width = 64
            height = 64
            flatten = -1
            model = 'keras/animals/model.model'
            label_bin = 'keras/animals/model_labels.pickle'
            predictions, label = self.predict_category(img, width, height, flatten, model, label_bin)

            results['preds'] = predictions
            results['max'] = label
            results['status'] = True
            results['img'] = img

analyzer/templates/dashboard/home/home.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}
    Image Anlyzer | Dashboard
{% endblock %}

{% block content %}
    <!-- BEGIN PAGE HEADER-->

    <h1 class="page-title"> Image Anlyzer Dashboard
        <small></small>
    </h1>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{% url 'analyzer:home' %}">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <span>Dashboard</span>
            </li>
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-fit-height blue dropdown-toggle" data-toggle="dropdown"
                        data-hover="dropdown" data-delay="1000" data-close-others="true"> Actions
                    <i class="fa fa-angle-down"></i>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li>
                        <a id="add_new" data-url="{% url 'analyzer:category_create' %}" data-modal="#general_modal">
                            <i class="fa fa-picture-o"></i> New Category</a>
                    </li>
                    <li>
                        <a id="add_new" data-url="{% url 'analyzer:image_create' %}" data-modal="#general_modal">
                            <i class="fa fa-upload"></i> Upload Image</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
    <!-- END PAGE HEADER-->
    <div class="row">
        <div class="col-md-12">
            <div class="note note-info">
                <h4 class="block">Hi
                    {% if user.get_full_name %}
                        {{ user.get_full_name }}
                    {% else %}
                        {{ user.get_username }}
                    {% endif %}!
                </h4>
                <p></p>
            </div>
        </div>
    </div>

    <div class="portfolio-content portfolio-1">
        <div class="categories_list"></div>
        <div class="images_list"></div>
    </div>

{% endblock %}

{% block modals %}
    <!-- General Modal -->
    <div id="general_modal" class="modal fade" data-backdrop="static" tabindex="-1" data-width="760">
        <div class="modal-content">

        </div>
    </div>


{% endblock %}

{% block CSS_PAGE_LEVEL_PLUGINS %}
    {% include 'plugins/fileupload_css_page_level_plugins.html' %}
{% endblock %}

{% block CSS_THEME_GLOBAL_STYLES %}
    {% include 'plugins/fileupload_css_theme_global_styles.html' %}
{% endblock %}

{% block JS_PAGE_LEVEL_PLUGINS %}
    {% include 'plugins/fileupload_js_page_level_plugins.html' %}
{% endblock %}

{% block JS_FINAL_SCRIPTS %}
    <script src="{% static 'js/dropdown_components.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/helper_components.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/home.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        (function (window, $) {
            window.DjangoDataTables = window.DjangoDataTables || {};

            current_page = 1;
            App.setAssetsPath('{% static 'assets/' %}');
            App.setGlobalImgPath('/global/img/');

            var loadImages = function (page) {
                $.ajax({
                    url: '{% url 'analyzer:image_list' %}',
                    type: 'GET',
                    dataType: 'html',
                    data: {
                        block: page
                    },
                    beforeSend: function () {
                        App.blockUI({
                            target: $('.portlet'),
                            animate: true,
                            overlayColor: 'none'
                        });
                    },
                    complete: function () {
                        App.unblockUI($('.portlet'));
                    },

                    success: function (data) {
                        $(".images_list").html(data);
                        HelperComponents.loadDashboardPortfolio();
                    },
                    error: function (data) {
                        HelperComponents.showAjaxError(data);
                    },
                });
            };
            var loadCtegories = function () {
                $.ajax({
                    url: '{% url 'analyzer:category_list' %}',
                    type: 'GET',
                    dataType: 'html',
                    beforeSend: function () {
                        App.blockUI({
                            target: $('.portlet'),
                            animate: true,
                            overlayColor: 'none'
                        });
                    },
                    complete: function () {
                        App.unblockUI($('.portlet'));
                    },

                    success: function (data) {
                        $(".categories_list").html(data);
                    },
                    error: function (data) {
                        console.log(data)
                        HelperComponents.showAjaxError(data);
                    },
                });
            };

            loadCtegories();
            loadImages(current_page);

            $(document).on('click', '#add_new', HelperComponents.loadForm);
            $(document).on('click', '#show_categories', HelperComponents.loadForm);
            $(document).on('click', '.go_to', function (e) {
                e.preventDefault();
                page = $(this).data('go_to_page');
                loadImages(page);
            });
            $('#general_modal').on('submit', '#js-send-form', function (e) {
                e.preventDefault();

                var form = $(this);
                var modal = $('#general_modal');
                if (typeof window.DjangoDataTables != 'undefined')
                    var datatable = window.DjangoDataTables["datatable"];

                formData = new FormData(form[0]);


                $.ajax({
                    url: form.attr("action"),
                    data: formData,
                    type: form.attr("method"),
                    dataType: 'json',
                    contentType: false,
                    processData: false,
                    complete: function () {
                        App.unblockUI(modal.find('.modal-content'));
                        $('.btn_confirm').prop('disabled', false);
                        $('.btn_cancel').show().prop('disabled', false);
                    },
                    beforeSend: function () {
                        App.blockUI({
                            target: modal.find('.modal-content'),
                            customEMX: true,
                            overlayColor: '#666'
                        });
                        $(".modal-footer .percent_progress").show();
                        $(" .percent_label").text(0 + '%');
                        $('.btn_confirm').prop('disabled', true);
                        $('.btn_cancel').prop('disabled', true).hide();
                    },
                    success: function (data) {
                        if (data.form_is_valid) {
                            modal.modal("hide");
                            if (typeof datatable != 'undefined')
                                datatable.draw(false);
                            loadCtegories();
                            loadImages(1);

                            swal({
                                title: data.title,
                                text: data.msg,
                                type: "success",
                                allowOutsideClick: true,
                                showConfirmButton: false,
                                showCancelButton: true,
                                confirmButtonClass: "",
                                cancelButtonClass: "btn-success",
                                closeOnConfirm: false,
                                closeOnCancel: true,
                                confirmButtonText: "",
                                cancelButtonText: "OK",
                            });
                        } else {


                            modal.find(".modal-content").html(data.html_form);
                            App.alert({
                                container: modal.find('.modal-body'),
                                place: "preppend",
                                type: "danger",
                                message: "Invalid data. Please correct it before submit.",
                                close: true,
                                reset: false,
                                focus: true,
                                closeInSeconds: 10,
                                icon: 'fa fa-exclamation-triangle'
                            });
                        }
                    },
                    error: function (data) {
                        showAjaxError(data, modal);
                    },
                    xhr: function () {
                        var jqXHR = null;
                        if (window.ActiveXObject) {
                            jqXHR = new window.ActiveXObject("Microsoft.XMLHTTP");
                        } else {
                            jqXHR = new window.XMLHttpRequest();
                        }
                        //Upload progress
                        jqXHR.upload.addEventListener("progress", function (evt) {
                            if (evt.lengthComputable) {
                                var percentComplete = Math.round((evt.loaded * 100) / evt.total);
                                $(".modal-footer .progress-bar").css('width', percentComplete + '%').attr('aria-valuenow', percentComplete);
                                console.log('Uploaded percent', percentComplete);
                                $(" .percent_label").text(percentComplete + '%');
                            }
                        }, false);
                        //Download progress
                        jqXHR.addEventListener("progress", function (evt) {
                            if (evt.lengthComputable) {
                                var percentComplete = Math.round((evt.loaded * 100) / evt.total);
                            }
                        }, false);
                        return jqXHR;
                    },
                });

                return false;
            });


            $(document).on('click', '.add_new_user', function (e) {
                e.preventDefault();

                var btn = $(this);
                var datatable = window.DjangoDataTables["CategoryDatatable"];
                var category_id = $(".categories-select2").find(':selected').val();
                var data = {
                    'category_id': category_id,
                    'csrfmiddlewaretoken': csrftoken
                };

                HelperComponents.addItemAJAX(category_id, btn, data, "Category", datatable);
                $(".categories-select2").val("").trigger("change");

                loadCtegories();
                loadImages(1);
                return false;
            });

            $(document).on('click', '.js-remove-category', function (e) {
                e.preventDefault();

                var btn = $(this);
                var datatable = window.DjangoDataTables["CategoryDatatable"];
                var category_id = btn.data('category-id');
                var data = {
                    'category_id': category_id,
                    'csrfmiddlewaretoken': csrftoken
                };

                HelperComponents.removeItemAJAX(category_id, btn, data, "Category", datatable);
                $(".categories-select2").val("").trigger("change");

                loadCtegories();
                loadImages(1);
                return false;
            });

        })(window, jQuery);
    </script>

{% endblock %}

analyzer/templates/dashboard/home/predict.html
<div class="portfolio-content">
    <div class="cbp-l-project-title">Prediction Results</div>


    <div class="cbp-l-project-container">
        <div class="cbp-l-project-details">
            <div class="cbp-l-project-details-title">
                <span>RESULTS</span>
            </div>
            <ul class="cbp-l-project-details-list">
                {% for cat,value in results.preds.items %}
                    {% if cat == results.max %}
                        <li class="font-yellow-gold bold" style="font-size: 16px;">
                            <strong class="font-yellow-gold bold">{{ cat.upper }}</strong>{{ value }} %
                        </li>
                    {% else %}
                        <li class="font-grey-cascade" style="font-size: 16px;">
                            <strong class="font-grey-cascade">{{ cat.upper }}</strong>{{ value }} %
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="cbp-l-project-desc">
            <div class="cbp-l-project-desc-title">
                <span>IMAGE</span>
            </div>
            <img class="img-responsive" src="{{ results.img.image.url }}"/>
        </div>

    </div>

    <br>
    <br>
    <br></div>