analyzer/urls.py
from django.conf.urls.static import static
from django.urls import path

from imganalyzer import settings
from . import views
from analyzer import views as analyzer_views

app_name = 'analyzer'

urlpatterns = [

    # Home
    path('', analyzer_views.Home.as_view(), name='home'),

    # Images
    path('image/create', analyzer_views.ImageForm.as_view(), name='image_create'),
    path('image/list', analyzer_views.ImageList.as_view(), name='image_list'),
    path('datatable/image/<pk>/categories', views.ImageCategoriesDatatable.as_view(), name='image_categories_dt'),
    path('image/<pk>/category/add', views.ImageCategoryAdd.as_view(), name='image_category_add'),
    path('image/<pk>/category/remove', views.ImageCategoryRemove.as_view(), name='image_category_remove'),

    # Category
    path('category/create', analyzer_views.CategoryForm.as_view(), name='category_create'),
    path('category/list', analyzer_views.CategoryList.as_view(), name='category_list'),
    path('image/<pk>/categories/update', analyzer_views.ImageCategoriesUpdate.as_view(), name='image_cat_update'),
    path('category/ajax_list', analyzer_views.CategoryAjaxList.as_view(), name='category_ajax_list'),

    path('datatable/categories', analyzer_views.CategoriesDatatable.as_view(), name='categories_dt'),
    path('categories', analyzer_views.CategoriesListView.as_view(), name='categories'),
    path('categories/remove', analyzer_views.CategoriesRemove.as_view(), name='categories_remove'),
    path('category/update/<pk>', analyzer_views.CategoryForm.as_view(), name='category_update'),

    path('predict/image/<pk>', analyzer_views.PredictImageCategory.as_view(), name='predict_image'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imganalyzer/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from analyzer import views as analyzer_views

urlpatterns = [

    path('', include('analyzer.urls', namespace='analyzer')),

    # Auth
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login'), name='logout'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done', analyzer_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    # Admin
    path('admin/', admin.site.urls),
]

analyzer/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500, unique=True)
    description = models.TextField(null=True, blank=True)

    def _generate_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        i = 1
        while Category.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, i)
            i += 1
        return unique_slug

    def __str__(self):
        return self.title


class Image(models.Model):
    STATUS_CHOICES = (
        ('fake', 'Fake'),
        ('real', 'Real'),
        ('not_analyzed', 'Not Analyzed')
    )

    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500, unique=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='analyzer_images')
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='images')
    size = models.IntegerField()
    extension = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='not_analyzed')
    categories = models.ManyToManyField(Category)

    def _get_extension(self):
        name, extension = os.path.splitext(self.image.name)
        return extension

    # It Generates a unique slug based on the existent Images in database
    def _generate_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        i = 1
        while Image.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, i)
            i += 1
        return unique_slug

    def save_model(self, request, obj, form, change):
        if not obj.id:
            obj.created_by = request.user
            obj.slug = obj._generate_unique_slug()
            obj.extension = obj.image._get_extension()
        super().save_model(request, obj, form, change)

    def save(self, *args, **kwargs):
        if not self.size and self.image.size > 0:
            self.size = self.image.size
        else:
            self.size = 0
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

analyzer/forms.py
from django import forms
from django.contrib.auth.models import Group

from analyzer.models import Image, Category


class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('image','title','description',)

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title', 'description',)

analyzer/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import PasswordContextMixin
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import TemplateView, FormView, ListView, DetailView

# Home Template View
from django.views.generic.base import View
from django_datatables_view.base_datatable_view import BaseDatatableView

from analyzer.forms import ImageForm, CategoryForm
from analyzer.helpers import AjaxResponseMixin, AJAXLoadMixin, AJAXDropdownMixin, AJAXMixin, RemoveObjectsMixin
from analyzer.models import Category, Image
from analyzer.helpers import DatatableTransformations as dt_helper

from keras.models import load_model
import argparse
import pickle
import cv2
from keras import backend as K


class Home(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/home/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_info'] = self.request.user
        context['category_count'] = Category.objects.count()
        context['images_count'] = Image.objects.count()
        return context

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class PasswordResetDoneView(PasswordContextMixin, TemplateView):
    template_name = 'registration/login.html'
    title = ('Password reset sent')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['password_reset_done'] = True
        return context


class ImageForm(LoginRequiredMixin, AjaxResponseMixin, View):
    template_name = 'dashboard/image/image_form.html'  # Form modal template
    modal_title = ''  # Modal title that should be displayed
    model = Image  # Model of this Class based view
    form_class = ImageForm  # Form of this Model

    def saveFormLogic(self, form):
        img = form.save(commit=False)
        img.created_by = self.request.user
        img.slug = img._generate_unique_slug()
        img.extension = img._get_extension()
        if not img.size and img.image.size > 0:
            img.size = img.image.size
        else:
            img.size = 0
        img.save()
        return img


class CategoryForm(LoginRequiredMixin, AjaxResponseMixin, FormView):
    template_name = 'dashboard/image/category_form.html'  # Form modal template
    modal_title = ''  # Modal title that should be displayed
    model = Category  # Model of this Class based view
    form_class = CategoryForm  # Form of this Model

    def saveFormLogic(self, form):
        category = form.save(commit=False)
        category.slug = category._generate_unique_slug()
        category.save()
        return category


class ImageList(LoginRequiredMixin, ListView):
    template_name = 'dashboard/image/image_list.html'
    model = Image
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        if not request.GET._mutable:
            request.GET._mutable = True
        request.GET['page'] = request.GET['block']

        return super().get(self, request, *args, **kwargs)


class CategoryList(LoginRequiredMixin, ListView):
    template_name = 'dashboard/image/category_list.html'
    model = Category
    paginate_by = 50


class ImageCategoriesUpdate(LoginRequiredMixin, AJAXLoadMixin, DetailView):
    model = Image
    template_name = 'dashboard/image/image_categories_update.html'
    modal_title = 'Image Categories'
    add_context = {}
    object = None

    def get(self, request, pk=None, *args, **kwargs):
        if pk is not None:
            self.object = get_object_or_404(self.model, pk=pk)
            self.add_context = {}
        return self.loadAJAXResponse()


class CategoryAjaxList(LoginRequiredMixin, AJAXDropdownMixin, ListView):
    model = Category

    def query(self, find, pk):

        if find is not None:
            object_list = self.model.objects.filter(title__contains=find).order_by('-id')[:20]
        else:
            object_list = self.model.objects.order_by('-id')[:20]

        result = list()

        for item in object_list:
            result.append({
                'id': item.id,
                'name': item.title
            })
        return result


class ImageCategoriesDatatable(LoginRequiredMixin, BaseDatatableView):
    model = Category
    columns = ['title', 'actions']
    max_display_length = 500

    def get_initial_queryset(self):
        pk = self.kwargs['pk']
        if not pk:
            raise NotImplementedError("Need to provide a model or implement get_initial_queryset!")
        image = Image.objects.get(pk=pk)
        return self.model.objects.filter(image__exact=image)

    def render_column(self, row, column):
        pk = self.kwargs['pk']
        image = Image.objects.get(pk=pk)
        if column == 'title':
            return dt_helper.highlightBlue(row.title)
        elif column == 'actions':
            return render_to_string('dashboard/image/image_categories_dt_buttons.html',
                                    {"category": row, 'image': image})
        else:
            return super(ImageCategoriesDatatable, self).render_column(row, column)


class ImageCategoryRemove(LoginRequiredMixin, PermissionRequiredMixin, AJAXLoadMixin, DetailView):
    permission_required = 'foundation.change_account'
    model = Image
    template_name = 'dashboard/image/image_categories_update.html'
    modal_title = 'Image Categories'
    add_context = {}
    object = None

    def post(self, request, pk=None, *args, **kwargs):
        if pk is not None:
            image = get_object_or_404(self.model, pk=pk)
            category_id = self.request.POST.get('category_id')
            category = Category.objects.get(id=category_id)
            cnt = image.categories.count()
            image.categories.remove(category)
            if image.categories.count() < cnt:
                self.add_context['status'] = True
                self.add_context['title'] = 'Success'
                self.add_context['msg'] = 'Category ' + str(category.title) + ' has been removed'
            else:
                self.add_context['status'] = False
                self.add_context['title'] = 'Fail'
                self.add_context['msg'] = 'Impossible to remove ' + str(category.title) + ''

            self.object = image

        return self.loadAJAXResponse()


class ImageCategoryAdd(LoginRequiredMixin, PermissionRequiredMixin, AJAXLoadMixin, DetailView):
    permission_required = 'foundation.change_account'
    model = Image
    template_name = 'dashboard/image/image_categories_update.html'
    modal_title = 'Image Categories'
    add_context = {}
    object = None

    def post(self, request, pk=None, *args, **kwargs):
        if pk is not None:
            image = get_object_or_404(self.model, pk=pk)
            category_id = self.request.POST.get('category_id')
            category = Category.objects.get(id=category_id)

            if category in image.categories.all():
                self.add_context['status'] = False
                self.add_context['title'] = 'Fail'
                self.add_context['msg'] = 'This category is already included!'
            else:
                cnt = image.categories.count()
                image.categories.add(category)
                if image.categories.count() > cnt:
                    self.add_context['status'] = True
                    self.add_context['title'] = 'Success'
                    self.add_context['msg'] = 'Category ' + str(category.title) + ' has been included!'
                else:
                    self.add_context['status'] = False
                    self.add_context['title'] = 'Fail'
                    self.add_context['msg'] = 'Impossible to include ' + str(category.title)

            self.object = image

        return self.loadAJAXResponse()


class CategoriesDatatable(LoginRequiredMixin, BaseDatatableView):
    model = Category
    columns = ['check',
               'title',
               'slug',
               'description',
               'actions']
    order_columns = columns
    max_display_length = 500

    def render_column(self, row, column):
        if column == 'check':
            return dt_helper.generateRowCheckBox(row.id)
        if column == 'title':
            return dt_helper.highlightOrange(row.title)
        if column == 'slug':
            return dt_helper.printSlug(row.slug)
        elif column == 'actions':
            return render_to_string('dashboard/category/partial_datatable_buttons.html', {"category": row})
        else:
            return super(CategoriesDatatable, self).render_column(row, column)


class CategoriesListView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/category/categories.html'


class CategoriesRemove(LoginRequiredMixin, AJAXMixin, RemoveObjectsMixin, View):
    model = Category

    # Deletion Logic
    def deleteObject(self, object):
        name = '<b>' + object.title + '</b> - '
        if object.delete():
            return (None, None)
        else:
            return ('error', name + 'Impossible to remove')


class PredictImageCategory(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/home/predict.html'

    def get(self, request, *args, **kwargs):
        results = {}

        if 'pk' in kwargs:

            # try:

            img = Image.objects.get(pk=kwargs['pk'])
            width = 64
            height = 64
            flatten = -1
            model = 'keras/animals/model.model'
            label_bin = 'keras/animals/model_labels.pickle'
            predictions, label = self.predict_category(img, width, height, flatten, model, label_bin)

            results['preds'] = predictions
            results['max'] = label
            results['status'] = True
            results['img'] = img

analyzer/templates/dashboard/image/category_form.html
{% load widget_tweaks %}


<form method="POST" action="{{ request_path }}" id="js-send-form" enctype="multipart/form-data" novalidate>
    {% csrf_token %}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">{{ modal_title }}</h4>
    </div>
    <div class="modal-body">

        <div class="row">
            {% for field in form %}

                    <div class="col-lg-12">
                        <div class="form-group{% if field.errors %} has-error{% endif %} {{ field|field_type }} {{ field|widget_type }} {{ field.html_name }}">
                            <label for="{{ field.id_for_label }}"><b>{{ field.label }}</b></label>
                            {% render_field field class="form-control" %}
                            {% for error in field.errors %}
                                <p class="help-block">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>

            {% endfor %}
        </div>
    </div>
    <div class="modal-footer">
        <div class="row percent_progress" style="display: none;">
            <div class="col-lg-10">
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="80"
                         aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                        <span class="sr-only"> 0%</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-2"><span class="badge label-primary percent_label"></span></div>
        </div>
        <button type="button" class="btn_cancel btn dark btn-outline" data-dismiss="modal">Close</button>
        <button type="submit" class="btn_confirm btn btn-primary"><i class="fas fa-save"></i> Save</button>
    </div>
</form>

analyzer/templates/dashboard/image/category_list.html
{% if object_list|length == 0 %}
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        <strong>Hey!</strong> There is no any Category. You can create the first one on the Actions menu button above.
    </div>
{% else %}
    <div id="js-image-filters" class="cbp-l-filters-button">
        <div data-filter="*" class="cbp-filter-item-active cbp-filter-item btn dark btn-outline uppercase"> All
            <div class="cbp-filter-counter"></div>
        </div>
        {% for category in object_list %}
            <div data-filter=".{{ category.slug }}"
                 class="cbp-filter-item btn dark btn-outline uppercase"> {{ category.title }}
                <div class="cbp-filter-counter"></div>
            </div>
        {% endfor %}
    </div>

{% endif %}

analyzer/templates/dashboard/image/image_categories_dt_buttons.html
<button href="javascript:;" class="btn btn-danger btn-xs pull-right js-remove-category" data-url="{% url 'analyzer:image_category_remove' image.id %}" data-category-id="{{ category.id }}" data-modal="">
    <i class="fa fa-trash"></i> Remove
</button>

analyzer/templates/dashboard/image/image_categories_update.html
<form method="POST" action="{{ request_path }}" id="add_category_form" novalidate>
    {% csrf_token %}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">{{ modal_title }} | {{ object.title }}</h4>
    </div>
    <div class="modal-body">
        <div class="row">

            <div class="col-lg-9">
                <div class="form-group">
                    <select class="form-control categories-select2"></select>
                </div>
            </div>
            <div class="col-lg-3">
                <button class="btn btn-primary btn-block add_new_user"
                        data-url="{% url 'analyzer:image_category_add' object.id %}"> Include Category
                </button>
            </div>

            <div class="col-lg-12">
                <section class="adv-table " id="no-more-tables">
                    <table class="display table table-hover table-striped table-condensed cf"
                           id="CategoryDatatable" cellspacing="0" width="100%">
                    </table>
                </section>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn_cancel btn dark btn-outline" data-dismiss="modal">Close</button>
    </div>
</form>

<script type="text/javascript">

    (function (window, $) {


        var url = "{% url 'analyzer:category_ajax_list' %}";
        var placeholder = 'Select a Category';
        var element = ".categories-select2";
        var pk = 1;
        var parent = $("#add_category_form").closest(".modal");

        DropDownComponents.initDefaultAjaxDropDown(url, placeholder, element,pk,parent);




        window.DjangoDataTables["CategoryDatatable"] = $("#CategoryDatatable").DataTable({
            "serverSide": true,
            "processing": true,
            "bLengthChange": false,
            "ajax": {
                "url": "{% url 'analyzer:image_categories_dt' object.id %}",
                "method": "GET",
                "async": false,
            },
            "order": [[0, "asc"]],
            "columns": [
                {
                    "name": "title",
                    "data": 0,
                    "title": "Category",
                    "orderable": true,
                    "searchable": true
                },
                {
                    "name": "actions",
                    "data": 1,
                    "title": "",
                    "orderable": false,
                    "searchable": false
                },
            ]
        });


    })(window, jQuery);
</script>

analyzer/templates/dashboard/image/image_form.html
{% load widget_tweaks %}


<form method="POST" action="{{ request_path }}" id="js-send-form" enctype="multipart/form-data" novalidate>
    {% csrf_token %}

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">{{ modal_title }}</h4>
    </div>
    <div class="modal-body">

        <div class="row">
            {% for field in form %}
                {% if field|field_type == 'imagefield' %}
                    <div class="col-lg-4">
                        <div class="form-group{% if field.errors %} has-error{% endif %}">
                            <label class="control-label"><b>{{ field.html_name|title }}</b></label>
                            <div class="">
                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput"
                                         style="width: 200px; height: 150px;">
                                        {% if field.value != None and field.value != '' and not field.errors %}
                                            <img src="media/{{ field.value }}"/>
                                        {% endif %}
                                    </div>
                                    <div>
                                <span class="btn red btn-outline btn-file">
                                    <span class="fileinput-new"> Select image </span>
                                    <span class="fileinput-exists"> Change </span>
                                      <input type="file" name="{{ field.html_name }}"
                                             accept="image/*" id="{{ field.id_for_label }}">
                                </span>

                                        <a href="javascript:;" class="btn red fileinput-exists"
                                           data-dismiss="fileinput">
                                            Remove
                                        </a>
                                    </div>
                                </div>


                                {% for error in field.errors %}
                                    <p class="help-block">{{ error }}</p>
                                {% endfor %}
                            </div>
                        </div>
                        {% if field.value != None and field.value != '' and not field.errors %}
                            <div class="mt-checkbox-list">
                                <label class="mt-checkbox"> Clear currently Logo
                                    <input type="checkbox" name="{{ field.html_name }}-clear"
                                           id="{{ field.html_name }}-clear_id">
                                    <span></span>
                                </label>
                            </div>
                        {% endif %}
                    </div>
                {% else %}
                    <div class="col-lg-8">
                        <div class="form-group{% if field.errors %} has-error{% endif %} {{ field|field_type }} {{ field|widget_type }} {{ field.html_name }}">
                            <label for="{{ field.id_for_label }}"><b>{{ field.label }}</b></label>
                            {% render_field field class="form-control" %}
                            {% for error in field.errors %}
                                <p class="help-block">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="modal-footer">
        <div class="row percent_progress" style="display: none;">
            <div class="col-lg-10">
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="80"
                         aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                        <span class="sr-only"> 0%</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-2"><span class="badge label-primary percent_label"></span></div>
        </div>
        <button type="button" class="btn_cancel btn dark btn-outline" data-dismiss="modal">Close</button>
        <button type="submit" class="btn_confirm btn btn-primary"><i class="fas fa-save"></i> Save</button>
    </div>
</form>

analyzer/templates/dashboard/image/image_list.html
{% load static %}

{% if object_list|length == 0 %}
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        <strong>Ops!</strong> There is no any images here. You can upload the first one on the Actions menu button
        above.
    </div>
{% endif %}

<div id="js-images" class="cbp">


    <div class="cbp-loadMore-block{{ page_obj.number }}">
        {% for image in object_list %}
            <div class="cbp-item {% for cat in image.categories.all %}{{ cat.slug }} {% endfor %}">
                <div class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{{ image.image.url }}" alt=""></div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignCenter">
                            <div class="cbp-l-caption-body">

                                <a href="{% url 'analyzer:predict_image' image.id %}"
                                   class="cbp-singlePage cbp-l-caption-buttonLeft btn blue uppercase uppercase"
                                   rel="nofollow" title="Anlyze it"><i class="fa fa-play-circle"></i> Predict
                                </a>

                                <a href="{{ image.image.url }}"
                                   class="cbp-lightbox cbp-l-caption-buttonRight btn blue uppercase uppercase"
                                   data-title="{{ image.title }}<br>{{ image.description }}" title="View Large"><i
                                        class="fa fa-expand"></i> View Large
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="cbp-l-grid-projects-title uppercase text-center uppercase text-center">{{ image.title }}</div>
                <div class="cbp-l-grid-projects-desc uppercase text-center uppercase text-center">{{ image.description }}</div>
                <div class="cbp-l-grid-projects-desc uppercase text-center uppercase text-center">
                    <a id="show_categories"
                       data-url="{% url 'analyzer:image_cat_update' image.id %}"
                       data-modal="#general_modal"
                       class="btn blue uppercase uppercase"
                       rel="nofollow"
                       title="Categories">
                        <i class="fa fa-picture-o"></i> Categories
                    </a>
                                        <a href="#"
                       class="btn red uppercase uppercase"
                       rel="nofollow"
                       title="Remove">
                        <i class="fa fa-trash"></i> Remove
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>

</div>


<div id="js-images-load-more" class="cbp-l-loadMore-button">
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a class="go_to" data-go_to_page="{{ page_obj.previous_page_number }}"
                       href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a class="go_to" data-go_to_page="{{ i }}" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a class="go_to" data-go_to_page="{{ page_obj.next_page_number }}"
                       href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
</div>